# Generated by Django 3.0.3 on 2020-02-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('availability', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], max_length=32, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate'), ('doctrate', 'Doctrate')], max_length=32, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('filled', 'Vacancy Filled')], default='draft', max_length=32)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.Category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.Language')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='opportunities.Skills')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
